name: 'Generate Auto Changelog'

on: push

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: "âœï¸ Generate changelog"
      id: generate-changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.2
      with:
        onlyLastTag: "true"
        stripHeaders: "true"
        stripGeneratorNotice: "true"
    - name: "ğŸ–¨ï¸ Print changelog to console"
      run: cat CHANGELOG.md
 
